### PR TITLE
Use full namespace for importing of Cache class

### PR DESCRIPTION
**Pull request by jbrooksuk**
If you're importing a class, make sure you use the full namespace.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Heh, my editor has trimmed some whitespace too. My other PR #9 may need to be merged first, then re-do this commit as it may not merge on top.

**Comment by freekmurze** [comment]
Thanks for your changes.
 #9 is merged.
Please submit #10 again so it doesn't give merge conflicts.

**Comment by jbrooksuk** [comment]
Can you re-open this PR? I've re-pushed the commits rebased on top of the new `master` branch :)

**Comment by jbrooksuk** [comment]
Actually, nevermind, I'll re-open :)

**Pull request closed without merging**
